/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        canvas: '#ffffff',
        'soft-stone': '#eeece7',
        'pale-green': '#edfce9',
        'pale-blue': '#f1f5ff',
        'card-border': '#f2f2f2',
        'surface-soft': '#f7f7f5',
        'surface-card': '#eeece7',
        'surface-cream-strong': '#eeece7',
        'surface-dark': '#17171c',
        'surface-dark-elevated': '#212121',
        'surface-dark-soft': '#0f0f13',
        'deep-green': '#003c33',
        'dark-navy': '#071829',
        ink: '#212121',
        body: '#212121',
        'body-strong': '#000000',
        muted: '#75758a',
        'muted-soft': '#93939f',
        hairline: '#d9d9dd',
        'hairline-soft': '#e5e7eb',
        primary: {
          DEFAULT: '#17171c',
          active: '#000000',
          disabled: '#e5e7eb',
          light: '#f2f2f2',
        },
        coral: {
          DEFAULT: '#ff7759',
          soft: '#ffad9b',
        },
        'action-blue': '#1863dc',
        'focus-blue': '#4c6ee6',
        'accent-teal': '#003c33',
        'accent-amber': '#ff7759',
        success: '#5db872',
        warning: '#d4a017',
        error: '#b30000',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        'on-dark-soft': '#93939f',
      },
      fontFamily: {
        sans: ['Inter', '"Unica77 Cohere Web"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Arial', 'sans-serif'],
        display: ['"Space Grotesk"', '"CohereText"', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"CohereMono"', 'ui-monospace', 'Menlo', 'Consolas', 'monospace'],
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '22px',
        '2xl': '30px',
        pill: '32px',
      },
    },
  },
  plugins: [],
}
